package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	var (
		dir = flag.String("dir", "service", "要扫描的根目录（默认为 service）")
	)
	flag.Parse()

	if err := scanAndGenerate(*dir); err != nil {
		fmt.Fprintf(os.Stderr, "错误: %v\n", err)
		os.Exit(1)
	}
}

// scanAndGenerate 递归扫描目录，找到所有 types.go 文件并生成对应的 types_gen.go
func scanAndGenerate(rootDir string) error {
	var count int
	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// 跳过 vendor 和隐藏目录
		if info.IsDir() {
			name := info.Name()
			if name == "vendor" || name == ".git" || name == "node_modules" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		// 只处理 types.go 文件
		if filepath.Base(path) != "types.go" {
			return nil
		}

		dir := filepath.Dir(path)
		outputFile := filepath.Join(dir, "types_gen.go")

		fmt.Printf("🔍 发现 types.go: %s\n", path)

		if err := generateBuilder(path, outputFile); err != nil {
			fmt.Printf("   ⚠️  跳过（无需生成）: %v\n", err)
			return nil
		}

		count++
		return nil
	})

	if err != nil {
		return err
	}

	fmt.Printf("\n✅ 完成！共处理 %d 个文件\n", count)
	return nil
}

func generateBuilder(inputFile, outputFile string) error {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, inputFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("解析文件失败: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/builder. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", node.Name.Name))

	hasContent := false

	// 遍历所有类型定义
	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		// 只处理以 Req 结尾的结构体
		structName := typeSpec.Name.Name
		if !strings.HasSuffix(structName, "Req") {
			return true
		}

		// 生成 New 函数
		buf.WriteString(fmt.Sprintf("func New%s() *%s {\n", structName, structName))
		buf.WriteString(fmt.Sprintf("\treturn &%s{}\n", structName))
		buf.WriteString("}\n\n")

		// 为每个指针字段生成 setter 方法
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue
			}

			fieldName := field.Names[0].Name

			// 只处理导出字段（大写开头）的指针字段
			if !ast.IsExported(fieldName) {
				continue
			}

			starExpr, ok := field.Type.(*ast.StarExpr)
			if !ok {
				continue
			}

			// 获取字段类型（去掉指针）
			var typeName string
			switch t := starExpr.X.(type) {
			case *ast.Ident:
				typeName = t.Name
			case *ast.SelectorExpr:
				typeName = fmt.Sprintf("%s.%s", t.X, t.Sel.Name)
			default:
				continue
			}

			// 方法名：With + 字段名
			methodName := "With" + fieldName

			// 参数名：将字段名首字母小写
			paramName := strings.ToLower(fieldName[:1]) + fieldName[1:]

			// 生成 setter 方法
			buf.WriteString(fmt.Sprintf("func (req *%s) %s(%s %s) *%s {\n",
				structName, methodName, paramName, typeName, structName))
			buf.WriteString(fmt.Sprintf("\treq.%s = &%s\n", fieldName, paramName))
			buf.WriteString("\treturn req\n")
			buf.WriteString("}\n\n")

			hasContent = true
		}

		return true
	})

	if !hasContent {
		return fmt.Errorf("没有找到需要生成 builder 方法的结构体")
	}

	// 格式化代码
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// 如果格式化失败，输出原始内容以便调试
		fmt.Println("格式化失败，输出原始内容:")
		fmt.Println(buf.String())
		return fmt.Errorf("格式化代码失败: %w", err)
	}

	// 写入文件
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		return fmt.Errorf("写入文件失败: %w", err)
	}

	fmt.Printf("   ✅ 生成: %s\n", outputFile)
	return nil
}
