// Code generated by cmd/builder. DO NOT EDIT.

package auth

func NewInternalAppAccessTokenReq() *InternalAppAccessTokenReq {
	return &InternalAppAccessTokenReq{}
}

func (req *InternalAppAccessTokenReq) WithAppId(appId string) *InternalAppAccessTokenReq {
	req.AppId = &appId
	return req
}

func (req *InternalAppAccessTokenReq) WithAppSecret(appSecret string) *InternalAppAccessTokenReq {
	req.AppSecret = &appSecret
	return req
}

func NewInternalTenantAccessTokenReq() *InternalTenantAccessTokenReq {
	return &InternalTenantAccessTokenReq{}
}

func (req *InternalTenantAccessTokenReq) WithAppId(appId string) *InternalTenantAccessTokenReq {
	req.AppId = &appId
	return req
}

func (req *InternalTenantAccessTokenReq) WithAppSecret(appSecret string) *InternalTenantAccessTokenReq {
	req.AppSecret = &appSecret
	return req
}
