// Code generated by cmd/builder. DO NOT EDIT.

package im

import (
	"fmt"
	"strconv"

	"github.com/lllllan02/larkgo/core"
)

func NewI18nNames() *I18nNames {
	return &I18nNames{}
}

func (req *I18nNames) WithZhCn(zhCn string) *I18nNames {
	req.ZhCn = &zhCn
	return req
}

func (req *I18nNames) WithEnUs(enUs string) *I18nNames {
	req.EnUs = &enUs
	return req
}

func (req *I18nNames) WithJaJp(jaJp string) *I18nNames {
	req.JaJp = &jaJp
	return req
}

func NewRestrictedModeSetting() *RestrictedModeSetting {
	return &RestrictedModeSetting{}
}

func (req *RestrictedModeSetting) WithStatus(status bool) *RestrictedModeSetting {
	req.Status = &status
	return req
}

func (req *RestrictedModeSetting) WithScreenshotHasPermissionSetting(screenshotHasPermissionSetting PermissionLevel) *RestrictedModeSetting {
	req.ScreenshotHasPermissionSetting = &screenshotHasPermissionSetting
	return req
}

func (req *RestrictedModeSetting) WithDownloadHasPermissionSetting(downloadHasPermissionSetting PermissionLevel) *RestrictedModeSetting {
	req.DownloadHasPermissionSetting = &downloadHasPermissionSetting
	return req
}

func (req *RestrictedModeSetting) WithMessageHasPermissionSetting(messageHasPermissionSetting PermissionLevel) *RestrictedModeSetting {
	req.MessageHasPermissionSetting = &messageHasPermissionSetting
	return req
}

func NewCreateChatReq() *CreateChatReq {
	return &CreateChatReq{
		query: make(core.QueryParams),
	}
}

func (req *CreateChatReq) UserIdType(userIdType UserIdType) *CreateChatReq {
	req.query.Set("user_id_type", fmt.Sprintf("%v", userIdType))
	return req
}

func (req *CreateChatReq) SetBotManager(setBotManager bool) *CreateChatReq {
	req.query.Set("set_bot_manager", strconv.FormatBool(setBotManager))
	return req
}

func (req *CreateChatReq) Uuid(uuid string) *CreateChatReq {
	req.query.Set("uuid", uuid)
	return req
}

func (req *CreateChatReq) WithName(name string) *CreateChatReq {
	req.Name = &name
	return req
}

func (req *CreateChatReq) WithI18nNames(i18nNames I18nNames) *CreateChatReq {
	req.I18nNames = &i18nNames
	return req
}

func (req *CreateChatReq) WithDescription(description string) *CreateChatReq {
	req.Description = &description
	return req
}

func (req *CreateChatReq) WithAvatar(avatar string) *CreateChatReq {
	req.Avatar = &avatar
	return req
}

func (req *CreateChatReq) WithOwnerId(ownerId string) *CreateChatReq {
	req.OwnerId = &ownerId
	return req
}

func (req *CreateChatReq) WithUserIdList(userIdList ...string) *CreateChatReq {
	req.UserIdList = userIdList
	return req
}

func (req *CreateChatReq) WithBotIdList(botIdList ...string) *CreateChatReq {
	req.BotIdList = botIdList
	return req
}

func (req *CreateChatReq) WithLabels(labels ...string) *CreateChatReq {
	req.Labels = labels
	return req
}

func (req *CreateChatReq) WithToolkitIds(toolkitIds ...string) *CreateChatReq {
	req.ToolkitIds = toolkitIds
	return req
}

func (req *CreateChatReq) WithChatTags(chatTags ...string) *CreateChatReq {
	req.ChatTags = chatTags
	return req
}

func (req *CreateChatReq) WithExternal(external bool) *CreateChatReq {
	req.External = &external
	return req
}

func (req *CreateChatReq) WithChatMode(chatMode ChatMode) *CreateChatReq {
	req.ChatMode = &chatMode
	return req
}

func (req *CreateChatReq) WithChatType(chatType ChatType) *CreateChatReq {
	req.ChatType = &chatType
	return req
}

func (req *CreateChatReq) WithGroupMessageType(groupMessageType GroupMessageType) *CreateChatReq {
	req.GroupMessageType = &groupMessageType
	return req
}

func (req *CreateChatReq) WithMembershipApproval(membershipApproval MembershipApproval) *CreateChatReq {
	req.MembershipApproval = &membershipApproval
	return req
}

func (req *CreateChatReq) WithJoinMessageVisibility(joinMessageVisibility MessageVisibility) *CreateChatReq {
	req.JoinMessageVisibility = &joinMessageVisibility
	return req
}

func (req *CreateChatReq) WithLeaveMessageVisibility(leaveMessageVisibility MessageVisibility) *CreateChatReq {
	req.LeaveMessageVisibility = &leaveMessageVisibility
	return req
}

func (req *CreateChatReq) WithUrgentSetting(urgentSetting PermissionLevel) *CreateChatReq {
	req.UrgentSetting = &urgentSetting
	return req
}

func (req *CreateChatReq) WithVideoConferenceSetting(videoConferenceSetting PermissionLevel) *CreateChatReq {
	req.VideoConferenceSetting = &videoConferenceSetting
	return req
}

func (req *CreateChatReq) WithEditPermission(editPermission PermissionLevel) *CreateChatReq {
	req.EditPermission = &editPermission
	return req
}

func (req *CreateChatReq) WithPinManageSetting(pinManageSetting PermissionLevel) *CreateChatReq {
	req.PinManageSetting = &pinManageSetting
	return req
}

func (req *CreateChatReq) WithHideMemberCountSetting(hideMemberCountSetting PermissionLevel) *CreateChatReq {
	req.HideMemberCountSetting = &hideMemberCountSetting
	return req
}

func (req *CreateChatReq) WithRestrictedModeSetting(restrictedModeSetting RestrictedModeSetting) *CreateChatReq {
	req.RestrictedModeSetting = &restrictedModeSetting
	return req
}

func NewDeleteChatReq() *DeleteChatReq {
	return &DeleteChatReq{
		path: make(core.PathParams),
	}
}

func (req *DeleteChatReq) ChatId(chatId string) *DeleteChatReq {
	req.path.Set("chat_id", chatId)
	return req
}

func NewGetChatReq() *GetChatReq {
	return &GetChatReq{
		query: make(core.QueryParams),
		path:  make(core.PathParams),
	}
}

func (req *GetChatReq) UserIdType(userIdType UserIdType) *GetChatReq {
	req.query.Set("user_id_type", fmt.Sprintf("%v", userIdType))
	return req
}

func (req *GetChatReq) ChatId(chatId string) *GetChatReq {
	req.path.Set("chat_id", chatId)
	return req
}

func NewLinkChatReq() *LinkChatReq {
	return &LinkChatReq{
		path: make(core.PathParams),
	}
}

func (req *LinkChatReq) ChatId(chatId string) *LinkChatReq {
	req.path.Set("chat_id", chatId)
	return req
}

func (req *LinkChatReq) WithValidityPeriod(validityPeriod ValidityPeriod) *LinkChatReq {
	req.ValidityPeriod = &validityPeriod
	return req
}

func NewListChatReq() *ListChatReq {
	return &ListChatReq{
		query: make(core.QueryParams),
	}
}

func (req *ListChatReq) UserIdType(userIdType UserIdType) *ListChatReq {
	req.query.Set("user_id_type", fmt.Sprintf("%v", userIdType))
	return req
}

func (req *ListChatReq) SortType(sortType ChatSortType) *ListChatReq {
	req.query.Set("sort_type", fmt.Sprintf("%v", sortType))
	return req
}

func (req *ListChatReq) PageToken(pageToken string) *ListChatReq {
	req.query.Set("page_token", pageToken)
	return req
}

func (req *ListChatReq) PageSize(pageSize int) *ListChatReq {
	req.query.Set("page_size", strconv.FormatInt(int64(pageSize), 10))
	return req
}

func NewSearchChatReq() *SearchChatReq {
	return &SearchChatReq{
		query: make(core.QueryParams),
	}
}

func (req *SearchChatReq) UserIdType(userIdType UserIdType) *SearchChatReq {
	req.query.Set("user_id_type", fmt.Sprintf("%v", userIdType))
	return req
}

func (req *SearchChatReq) Query(query string) *SearchChatReq {
	req.query.Set("query", query)
	return req
}

func (req *SearchChatReq) PageToken(pageToken string) *SearchChatReq {
	req.query.Set("page_token", pageToken)
	return req
}

func (req *SearchChatReq) PageSize(pageSize int) *SearchChatReq {
	req.query.Set("page_size", strconv.FormatInt(int64(pageSize), 10))
	return req
}
